name: barber_salon
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.8.2
  provider: ^6.0.1

  google_sign_in: ^5.2.1
  flutter_svg: ^0.23.0+1

  firebase_core: ^1.10.0
  firebase_messaging: ^11.1.0
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.5
#  json_serializable: ^6.0.1
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
