name: barber_salon
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  async: ^2.8.2
  provider: ^6.0.1
  shared_preferences: ^2.0.9
  http: ^0.13.4

  google_sign_in: ^5.2.1
  flutter_svg: ^1.0.0

  firebase_core: ^1.10.5
  firebase_messaging: ^11.2.3
  firebase_auth: ^3.3.3
  cloud_firestore: ^3.1.4

  flutter_local_notifications: ^9.1.5

dev_dependencies:
  build_runner: ^2.1.5
#  json_serializable: ^6.0.1
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
